exclude: 'node_modules|migrations|.git'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language: python
        language_version: python3.8
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: ['--config=setup.cfg']
