os: linux
dist: xenial
language: python
services:
  - docker
python:
  - "3.8"
notifications:
  email: false
cache:
  pip: true


stages:
  - name: test
  - name: deploy-staging
    if: branch = develop


jobs:
  include:
  - stage: test
    before_script:
      - pip install codecov
      - docker-compose build
    script:
      - make run_tests
    after_success:
      - codecov
  - stage: deploy-staging
    script: skip
    deploy:
      provider: heroku
      app: openwiden-staging
      api_key: $HEROKU_AUTH_TOKEN
      on:
        branch: develop
