sudo: required
language: python
services:
  - docker
python:
  - "3.8"
notifications:
  email: false
cache:
  pip: true


jobs:
  include:
    - stage: build-docker-image
      name: "Build docker image"
      script:
        - VERSION=$(python -c "import openwiden; print(openwiden.get_version())")
        - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
        - docker build -t stefanitsky/openwiden-backend:"$VERSION" .
        - docker push stefanitsky/openwiden-backend:"$VERSION"
    - stage: test
      name: "Run all tests"
      script:
        - docker-compose build
        - make run_tests
    - stage: deploy-stage
      name: "Deploy staging version"
      if: branch = develop
      script:
        - echo "wip"
    - stage: deploy-production
      name: "Deploy production version"
      if: branch = master
      script:
        - echo "wip"
