os: linux
dist: xenial
language: python
services:
  - docker
python:
  - "3.8"
notifications:
  email: false
cache:
  pip: true


stages:
  - name: test


jobs:
  include:
  - stage: test
    before_script:
      - touch ./docker/.env
      - docker-compose build
    script:
      - make run_tests
