os: linux
dist: xenial
language: python
services:
  - docker
python:
  - "3.8"
notifications:
  email: false
cache:
  pip: true


stages:
  - name: build-stage-image
    if: branch = develop
  - name: test
    if: branch = develop
  - name: build-production-image
    if: branch = master
  - name: deploy-staging
    if: branch = develop
  - name: deploy-production
    if: branch = master


jobs:
  include:
  - stage: build-stage-image
    script:
      - "./devops/docker_push_staging.sh"
  - stage: test
    script:
      - make COMPOSE_FILES=TEST_COMPOSE_FILES docker-compose command="build"
      - make COMPOSE_FILES=TEST_COMPOSE_FILES run_tests
  - stage: build-production-image
    script:
      - "./devops/docker_push_production.sh"
  - stage: deploy-staging
    script: skip
    deploy: &heroku
      provider: heroku
      app: openwiden-staging
      api_key: $HEROKU_AUTH_TOKEN
      on:
        branch: develop
  - stage: deploy-production
    script: skip
    deploy:
      <<: *heroku
      app: openwiden-production
      on:
        branch: master
