sudo: required
language: python
services:
  - docker
python:
  - "3.8"
notifications:
  email: false
cache:
  pip: true


jobs:
  include:
    - stage: build-stage-image
      if: branch = develop
      script:
        - ./devops/docker_push_stage.sh
    - stage: test
      script:
        - make COMPOSE_FILES=TEST_COMPOSE_FILES docker-compose command="build"
        - make COMPOSE_FILES=TEST_COMPOSE_FILES run_tests
    - stage: build-production-image
      if: branch = master
      script:
        - ./devops/docker_push_production.sh
