os: linux
dist: xenial
language: python
services:
  - docker
python:
  - "3.8"
notifications:
  email: false
cache:
  pip: true


stages:
  - name: test
#  - name: build-production-image
#    if: branch = master
  - name: deploy-staging
    if: branch = develop
#  - name: deploy-production
#    if: branch = master


jobs:
  include:
  - stage: test
    before_script:
      - docker-compose build
    script:
      - make run_tests
  - stage: deploy-staging
    script: skip
    deploy: &heroku
      provider: heroku
      app: openwiden-staging
      api_key: $HEROKU_AUTH_TOKEN
      on:
        branch: develop
#  - stage: deploy-production
#    script: skip
#    deploy:
#      <<: *heroku
#      app: openwiden-production
#      on:
#        branch: master
