version: "3.7"


services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - requirements_file=local.txt
    image: web
    volumes:
    - "./:/app"
    ports:
    - "8000:8000"
    env_file:
      - .envs/.local
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:12-alpine