version: '3.7'

services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    image: web
    build: .
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_CONFIGURATION
      - GITHUB_CLIENT_ID
      - GITHUB_SECRET_KEY
      - DJANGO_AWS_ACCESS_KEY_ID
      - DJANGO_AWS_SECRET_ACCESS_KEY
      - DJANGO_AWS_STORAGE_BUCKET_NAME
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
