version: '3.7'

services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      GITHUB_KEY: ${GITHUB_CLIENT_ID}
      GITHUB_SECRET: ${GITHUB_SECRET_KEY}
      DJANGO_CONFIGURATION: ${DJANGO_CONFIGURATION}
      DJANGO_AWS_ACCESS_KEY_ID: ${DJANGO_AWS_ACCESS_KEY_ID}
      DJANGO_AWS_SECRET_ACCESS_KEY: ${DJANGO_AWS_SECRET_ACCESS_KEY}
      DJANGO_AWS_STORAGE_BUCKET_NAME: ${DJANGO_AWS_STORAGE_BUCKET_NAME}
    image: web
    build: .
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
