version: "3.7"

services:
  db:
    image: postgres:11.6
  cache:
    image: redis:5.0
  web:
    restart: always
    image: &web web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash ./docker/run_server.sh
    env_file: &env
      - ./docker/.env
    environment:
      - CODECOV_TOKEN
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - DJANGO_SETTINGS_MODULE
      - DJANGO_CONFIGURATION
      - DJANGO_ALLOWED_HOSTS
      - SENTRY_DSN
      - GITHUB_CLIENT_ID
      - GITHUB_SECRET_KEY
      - GITLAB_APP_ID
      - GITLAB_SECRET
      - GITLAB_PRIVATE_TOKEN
      - REDIS_URL
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_API_URL
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
      - tasks
  tasks:
    restart: always
    image: *web
    env_file: *env
    command: bash -c "python manage.py qcluster"
