name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose -f local.yml build
    - name: Migrate
      run: docker-compose -f local.yml run --rm django python manage.py migrate
    - name: Up
      run: docker-compose -f local.yml up -d
    - name: Test
      run: docker-compose -f local.yml run django pytest
