name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose -f local.yml build
    - name: Migrate
      run: docker-compose -f local.yml run --rm django python manage.py migrate
    - name: Up
      run: docker-compose -f local.yml up -d
    - name: Tests & coverage report generate
      run: docker-compose -f local.yml run django pytest --cov-config=.coveragerc --cov=./ --cov-report=xml
#    - name: Save selenium screenshots as artifacts
#      uses: actions/upload-artifact@v2
#      if: always()
#      with:
#        name: selenium
#        path: openwiden/users/tests/selenium/
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: staging
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          timeout: 5s
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          script: |
            cd backend
            git pull
            docker-compose -f production.yml up -d --build
      - name: production
        uses: appleboy/ssh-action@master
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          timeout: 5s
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_PRIVATE_KEY }}
          script: |
            cd backend
            git pull
            docker-compose -f production.yml up -d --build
