name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose -f local.yml build
    - name: Migrate
      run: docker-compose -f local.yml run --rm django python manage.py migrate
    - name: Up
      run: docker-compose -f local.yml up -d
    - name: Tests & coverage report generate
      run: docker-compose -f local.yml run django pytest --cov-config=.coveragerc --cov=./ --cov-report=xml
#    - name: Save selenium screenshots as artifacts
#      uses: actions/upload-artifact@v2
#      if: always()
#      with:
#        name: selenium
#        path: openwiden/users/tests/selenium/
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
